version: '3'
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
      - '5432:5432'
    volumes:
      - ./postgres:/data/postgres
    env_file:
      - docker.env
    restart: always

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
      - '8080:80'
    volumes:
      - ./pgadmin:/root/.pgadmin
    env_file:
      - docker.env
    restart: always
    depends_on:
      - postgres
    links:
      - postgres:postgres
